# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_table.ui'
#
# Created: Fri Dec  5 21:40:18 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_createTable(object):
    def setupUi(self, createTable):
        createTable.setObjectName(_fromUtf8("createTable"))
        createTable.setWindowModality(QtCore.Qt.ApplicationModal)
        createTable.resize(860, 640)
        createTable.setMinimumSize(QtCore.QSize(600, 400))
        createTable.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(createTable)
        self.buttonBox.setGeometry(QtCore.QRect(10, 600, 391, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.moreButton = QtGui.QPushButton(createTable)
        self.moreButton.setGeometry(QtCore.QRect(10, 600, 111, 31))
        self.moreButton.setObjectName(_fromUtf8("moreButton"))
        self.frame = QtGui.QFrame(createTable)
        self.frame.setGeometry(QtCore.QRect(460, 10, 392, 621))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget = QtGui.QTabWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(390, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.nullTab = QtGui.QWidget()
        self.nullTab.setObjectName(_fromUtf8("nullTab"))
        self.layoutWidget = QtGui.QWidget(self.nullTab)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 21, 361, 471))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.nullCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.nullCheckBox.setObjectName(_fromUtf8("nullCheckBox"))
        self.gridLayout_3.addWidget(self.nullCheckBox, 0, 0, 1, 2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.defaultLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.defaultLineEdit.setObjectName(_fromUtf8("defaultLineEdit"))
        self.horizontalLayout_11.addWidget(self.defaultLineEdit)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_11.addWidget(self.label_12)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 2)
        self.minSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.minSpinBox.setMinimum(-999999999)
        self.minSpinBox.setMaximum(99999999)
        self.minSpinBox.setObjectName(_fromUtf8("minSpinBox"))
        self.gridLayout_3.addWidget(self.minSpinBox, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 1, 1, 1)
        self.maxSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.maxSpinBox.setMaximum(999999999)
        self.maxSpinBox.setProperty("value", 100)
        self.maxSpinBox.setObjectName(_fromUtf8("maxSpinBox"))
        self.gridLayout_3.addWidget(self.maxSpinBox, 3, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 4, 1, 1, 1)
        self.tabWidget.addTab(self.nullTab, _fromUtf8(""))
        self.validationTab = QtGui.QWidget()
        self.validationTab.setObjectName(_fromUtf8("validationTab"))
        self.label_15 = QtGui.QLabel(self.validationTab)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 351, 41))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.validList = QtGui.QListWidget(self.validationTab)
        self.validList.setGeometry(QtCore.QRect(10, 50, 361, 451))
        self.validList.setObjectName(_fromUtf8("validList"))
        self.tabWidget.addTab(self.validationTab, _fromUtf8(""))
        self.listTab = QtGui.QWidget()
        self.listTab.setObjectName(_fromUtf8("listTab"))
        self.label_16 = QtGui.QLabel(self.listTab)
        self.label_16.setGeometry(QtCore.QRect(10, 10, 361, 31))
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.enumList = QtGui.QListWidget(self.listTab)
        self.enumList.setGeometry(QtCore.QRect(10, 50, 371, 451))
        self.enumList.setObjectName(_fromUtf8("enumList"))
        self.tabWidget.addTab(self.listTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem2 = QtGui.QSpacerItem(20, 31, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.layoutWidget1 = QtGui.QWidget(createTable)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 230, 53, 98))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.addColumnBtn = QtGui.QToolButton(self.layoutWidget1)
        self.addColumnBtn.setMinimumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.addColumnBtn.setFont(font)
        self.addColumnBtn.setStyleSheet(_fromUtf8("QToolButton { color: rgb(0, 170, 0); }"))
        self.addColumnBtn.setObjectName(_fromUtf8("addColumnBtn"))
        self.gridLayout.addWidget(self.addColumnBtn, 0, 0, 1, 1)
        self.delColumnBtn = QtGui.QToolButton(self.layoutWidget1)
        self.delColumnBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.delColumnBtn.setBaseSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.delColumnBtn.setFont(font)
        self.delColumnBtn.setStyleSheet(_fromUtf8("QToolButton { color: rgb(188, 0, 0); }"))
        self.delColumnBtn.setObjectName(_fromUtf8("delColumnBtn"))
        self.gridLayout.addWidget(self.delColumnBtn, 1, 0, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(createTable)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 40, 401, 551))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget2)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 397, 523))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.layoutWidget3 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 371, 481))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label1 = QtGui.QLabel(self.layoutWidget3)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.horizontalLayout.addWidget(self.label1)
        self.fieldName1 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName1.setObjectName(_fromUtf8("fieldName1"))
        self.horizontalLayout.addWidget(self.fieldName1)
        self.fieldDataType1 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType1.setObjectName(_fromUtf8("fieldDataType1"))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.fieldDataType1.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.fieldDataType1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.fieldName2 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName2.setObjectName(_fromUtf8("fieldName2"))
        self.horizontalLayout_2.addWidget(self.fieldName2)
        self.fieldDataType2 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType2.setObjectName(_fromUtf8("fieldDataType2"))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.fieldDataType2.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.fieldDataType2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.fieldName3 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName3.setObjectName(_fromUtf8("fieldName3"))
        self.horizontalLayout_3.addWidget(self.fieldName3)
        self.fieldDataType3 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType3.setObjectName(_fromUtf8("fieldDataType3"))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.fieldDataType3.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.fieldDataType3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.fieldName4 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName4.setObjectName(_fromUtf8("fieldName4"))
        self.horizontalLayout_4.addWidget(self.fieldName4)
        self.fieldDataType4 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType4.setObjectName(_fromUtf8("fieldDataType4"))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.fieldDataType4.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.fieldDataType4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.fieldName5 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName5.setObjectName(_fromUtf8("fieldName5"))
        self.horizontalLayout_9.addWidget(self.fieldName5)
        self.fieldDataType5 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType5.setObjectName(_fromUtf8("fieldDataType5"))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.fieldDataType5.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.fieldDataType5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.fieldName6 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName6.setObjectName(_fromUtf8("fieldName6"))
        self.horizontalLayout_8.addWidget(self.fieldName6)
        self.fieldDataType6 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType6.setObjectName(_fromUtf8("fieldDataType6"))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.fieldDataType6.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.fieldDataType6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.fieldName7 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName7.setObjectName(_fromUtf8("fieldName7"))
        self.horizontalLayout_7.addWidget(self.fieldName7)
        self.fieldDataType7 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType7.setObjectName(_fromUtf8("fieldDataType7"))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.fieldDataType7.addItem(_fromUtf8(""))
        self.horizontalLayout_7.addWidget(self.fieldDataType7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.fieldName8 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName8.setObjectName(_fromUtf8("fieldName8"))
        self.horizontalLayout_6.addWidget(self.fieldName8)
        self.fieldDataType8 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType8.setObjectName(_fromUtf8("fieldDataType8"))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.fieldDataType8.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.fieldDataType8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.fieldName9 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName9.setObjectName(_fromUtf8("fieldName9"))
        self.horizontalLayout_5.addWidget(self.fieldName9)
        self.fieldDataType9 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType9.setObjectName(_fromUtf8("fieldDataType9"))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.fieldDataType9.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.fieldDataType9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.fieldName10 = QtGui.QLineEdit(self.layoutWidget3)
        self.fieldName10.setObjectName(_fromUtf8("fieldName10"))
        self.horizontalLayout_10.addWidget(self.fieldName10)
        self.fieldDataType10 = QtGui.QComboBox(self.layoutWidget3)
        self.fieldDataType10.setObjectName(_fromUtf8("fieldDataType10"))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.fieldDataType10.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.fieldDataType10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 2)
        self.layoutWidget4 = QtGui.QWidget(createTable)
        self.layoutWidget4.setGeometry(QtCore.QRect(60, 10, 341, 27))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setTextFormat(QtCore.Qt.RichText)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_12.addWidget(self.lineEdit)
        self.label1.setBuddy(self.fieldName1)
        self.label.setBuddy(self.fieldName2)
        self.label_2.setBuddy(self.fieldName3)
        self.label_3.setBuddy(self.fieldName4)
        self.label_4.setBuddy(self.fieldName5)
        self.label_5.setBuddy(self.fieldName6)
        self.label_6.setBuddy(self.fieldName7)
        self.label_7.setBuddy(self.fieldName8)
        self.label_8.setBuddy(self.fieldName9)
        self.label_9.setBuddy(self.fieldName10)
        self.label_17.setBuddy(self.lineEdit)

        self.retranslateUi(createTable)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), createTable.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), createTable.accept)
        QtCore.QObject.connect(self.moreButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.frame.setVisible)
        QtCore.QMetaObject.connectSlotsByName(createTable)
        createTable.setTabOrder(self.lineEdit, self.fieldName1)
        createTable.setTabOrder(self.fieldName1, self.fieldDataType1)
        createTable.setTabOrder(self.fieldDataType1, self.fieldName2)
        createTable.setTabOrder(self.fieldName2, self.fieldDataType2)
        createTable.setTabOrder(self.fieldDataType2, self.fieldName3)
        createTable.setTabOrder(self.fieldName3, self.fieldDataType3)
        createTable.setTabOrder(self.fieldDataType3, self.fieldName4)
        createTable.setTabOrder(self.fieldName4, self.fieldDataType4)
        createTable.setTabOrder(self.fieldDataType4, self.fieldName5)
        createTable.setTabOrder(self.fieldName5, self.fieldDataType5)
        createTable.setTabOrder(self.fieldDataType5, self.fieldName6)
        createTable.setTabOrder(self.fieldName6, self.fieldDataType6)
        createTable.setTabOrder(self.fieldDataType6, self.fieldName7)
        createTable.setTabOrder(self.fieldName7, self.fieldDataType7)
        createTable.setTabOrder(self.fieldDataType7, self.fieldName8)
        createTable.setTabOrder(self.fieldName8, self.fieldDataType8)
        createTable.setTabOrder(self.fieldDataType8, self.fieldName9)
        createTable.setTabOrder(self.fieldName9, self.fieldDataType9)
        createTable.setTabOrder(self.fieldDataType9, self.fieldName10)
        createTable.setTabOrder(self.fieldName10, self.fieldDataType10)
        createTable.setTabOrder(self.fieldDataType10, self.buttonBox)
        createTable.setTabOrder(self.buttonBox, self.tabWidget)
        createTable.setTabOrder(self.tabWidget, self.enumList)
        createTable.setTabOrder(self.enumList, self.scrollArea)
        createTable.setTabOrder(self.scrollArea, self.addColumnBtn)
        createTable.setTabOrder(self.addColumnBtn, self.delColumnBtn)
        createTable.setTabOrder(self.delColumnBtn, self.nullCheckBox)
        createTable.setTabOrder(self.nullCheckBox, self.defaultLineEdit)
        createTable.setTabOrder(self.defaultLineEdit, self.minSpinBox)
        createTable.setTabOrder(self.minSpinBox, self.maxSpinBox)
        createTable.setTabOrder(self.maxSpinBox, self.validList)
        createTable.setTabOrder(self.validList, self.moreButton)

    def retranslateUi(self, createTable):
        createTable.setWindowTitle(_translate("createTable", "Records - Create Table", None))
        self.moreButton.setText(_translate("createTable", "&Advanced >>", None))
        self.nullCheckBox.setText(_translate("createTable", "A value in this field is required. (NOT NULL)", None))
        self.defaultLineEdit.setPlaceholderText(_translate("createTable", "Default value", None))
        self.label_12.setText(_translate("createTable", "will be entered into this field automatically.", None))
        self.label_13.setText(_translate("createTable", "is the minimum value.", None))
        self.label_14.setText(_translate("createTable", "is the maximum value.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.nullTab), _translate("createTable", "&Data Options", None))
        self.label_15.setText(_translate("createTable", "Only allow the following formats of data to be included in this field.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.validationTab), _translate("createTable", "&Validation", None))
        self.label_16.setText(_translate("createTable", "Create a drop down menu of choices to choose from, for data such as the days of the week or place names.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.listTab), _translate("createTable", "Value &List", None))
        self.addColumnBtn.setToolTip(_translate("createTable", "Add a field after the existing columns.", None))
        self.addColumnBtn.setText(_translate("createTable", "+", None))
        self.delColumnBtn.setToolTip(_translate("createTable", "Remove a field - will remove data in this column!", None))
        self.delColumnBtn.setText(_translate("createTable", "-", None))
        self.label_10.setText(_translate("createTable", "<h3>Field Name</h3>", None))
        self.label_11.setText(_translate("createTable", "<h3>Data Type</h3>", None))
        self.label1.setText(_translate("createTable", "1.", None))
        self.fieldDataType1.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType1.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType1.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType1.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType1.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType1.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType1.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType1.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType1.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType1.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType1.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType1.setItemText(11, _translate("createTable", "foreign key", None))
        self.label.setText(_translate("createTable", "2.", None))
        self.fieldDataType2.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType2.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType2.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType2.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType2.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType2.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType2.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType2.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType2.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType2.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType2.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType2.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_2.setText(_translate("createTable", "3.", None))
        self.fieldDataType3.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType3.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType3.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType3.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType3.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType3.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType3.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType3.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType3.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType3.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType3.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType3.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_3.setText(_translate("createTable", "4.", None))
        self.fieldDataType4.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType4.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType4.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType4.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType4.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType4.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType4.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType4.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType4.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType4.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType4.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType4.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_4.setText(_translate("createTable", "5.", None))
        self.fieldDataType5.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType5.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType5.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType5.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType5.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType5.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType5.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType5.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType5.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType5.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType5.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType5.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_5.setText(_translate("createTable", "6.", None))
        self.fieldDataType6.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType6.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType6.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType6.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType6.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType6.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType6.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType6.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType6.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType6.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType6.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType6.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_6.setText(_translate("createTable", "7.", None))
        self.fieldDataType7.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType7.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType7.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType7.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType7.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType7.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType7.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType7.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType7.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType7.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType7.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType7.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_7.setText(_translate("createTable", "8.", None))
        self.fieldDataType8.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType8.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType8.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType8.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType8.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType8.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType8.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType8.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType8.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType8.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType8.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType8.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_8.setText(_translate("createTable", "9.", None))
        self.fieldDataType9.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType9.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType9.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType9.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType9.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType9.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType9.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType9.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType9.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType9.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType9.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType9.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_9.setText(_translate("createTable", "10.", None))
        self.fieldDataType10.setItemText(0, _translate("createTable", "text", None))
        self.fieldDataType10.setItemText(1, _translate("createTable", "decimal", None))
        self.fieldDataType10.setItemText(2, _translate("createTable", "whole number", None))
        self.fieldDataType10.setItemText(3, _translate("createTable", "long number", None))
        self.fieldDataType10.setItemText(4, _translate("createTable", "notes", None))
        self.fieldDataType10.setItemText(5, _translate("createTable", "date", None))
        self.fieldDataType10.setItemText(6, _translate("createTable", "timestamp", None))
        self.fieldDataType10.setItemText(7, _translate("createTable", "date time", None))
        self.fieldDataType10.setItemText(8, _translate("createTable", "True or False", None))
        self.fieldDataType10.setItemText(9, _translate("createTable", "Data blob", None))
        self.fieldDataType10.setItemText(10, _translate("createTable", "primary key", None))
        self.fieldDataType10.setItemText(11, _translate("createTable", "foreign key", None))
        self.label_17.setText(_translate("createTable", "<h2>Table Name:", None))

