# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query_2.ui'
#
# Created: Tue Mar 24 16:12:08 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(860, 594)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../images/win/records.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(8, 10, 841, 581))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.mainTabs = QtGui.QTabWidget(self.layoutWidget)
        self.mainTabs.setObjectName(_fromUtf8("mainTabs"))
        self.queryTypeTab = QtGui.QWidget()
        self.queryTypeTab.setObjectName(_fromUtf8("queryTypeTab"))
        self.layoutWidget1 = QtGui.QWidget(self.queryTypeTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 801, 481))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.newQueryBtn = QtGui.QRadioButton(self.layoutWidget1)
        self.newQueryBtn.setObjectName(_fromUtf8("newQueryBtn"))
        self.horizontalLayout.addWidget(self.newQueryBtn)
        self.newQueryName = QtGui.QLineEdit(self.layoutWidget1)
        self.newQueryName.setText(_fromUtf8(""))
        self.newQueryName.setObjectName(_fromUtf8("newQueryName"))
        self.horizontalLayout.addWidget(self.newQueryName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.editQueryBtn = QtGui.QRadioButton(self.layoutWidget1)
        self.editQueryBtn.setObjectName(_fromUtf8("editQueryBtn"))
        self.verticalLayout_2.addWidget(self.editQueryBtn)
        self.viewsGroupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.viewsGroupBox.setObjectName(_fromUtf8("viewsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.viewsGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.currentViewsList = QtGui.QListView(self.viewsGroupBox)
        self.currentViewsList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.currentViewsList.setObjectName(_fromUtf8("currentViewsList"))
        self.verticalLayout.addWidget(self.currentViewsList)
        self.verticalLayout_2.addWidget(self.viewsGroupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.typeGroupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.typeGroupBox.setObjectName(_fromUtf8("typeGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.typeGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.typeListWidget = QtGui.QListWidget(self.typeGroupBox)
        self.typeListWidget.setObjectName(_fromUtf8("typeListWidget"))
        self.verticalLayout_3.addWidget(self.typeListWidget)
        self.horizontalLayout_2.addWidget(self.typeGroupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.descrLabelTab1 = QtGui.QLabel(self.layoutWidget1)
        self.descrLabelTab1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.descrLabelTab1.setFrameShadow(QtGui.QFrame.Sunken)
        self.descrLabelTab1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descrLabelTab1.setWordWrap(True)
        self.descrLabelTab1.setObjectName(_fromUtf8("descrLabelTab1"))
        self.verticalLayout_4.addWidget(self.descrLabelTab1)
        self.mainTabs.addTab(self.queryTypeTab, _fromUtf8(""))
        self.condTab = QtGui.QWidget()
        self.condTab.setObjectName(_fromUtf8("condTab"))
        self.layoutWidget2 = QtGui.QWidget(self.condTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 790, 481))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tableLabel = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableLabel.sizePolicy().hasHeightForWidth())
        self.tableLabel.setSizePolicy(sizePolicy)
        self.tableLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.tableLabel.setObjectName(_fromUtf8("tableLabel"))
        self.horizontalLayout_3.addWidget(self.tableLabel)
        self.tableCombo = QtGui.QComboBox(self.layoutWidget2)
        self.tableCombo.setObjectName(_fromUtf8("tableCombo"))
        self.horizontalLayout_3.addWidget(self.tableCombo)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.fieldsLabel = QtGui.QLabel(self.layoutWidget2)
        self.fieldsLabel.setObjectName(_fromUtf8("fieldsLabel"))
        self.verticalLayout_5.addWidget(self.fieldsLabel)
        self.fieldsListTab2 = QtGui.QListView(self.layoutWidget2)
        self.fieldsListTab2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fieldsListTab2.setAlternatingRowColors(True)
        self.fieldsListTab2.setObjectName(_fromUtf8("fieldsListTab2"))
        self.verticalLayout_5.addWidget(self.fieldsListTab2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 42, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.compLabel = QtGui.QLabel(self.layoutWidget2)
        self.compLabel.setObjectName(_fromUtf8("compLabel"))
        self.verticalLayout_6.addWidget(self.compLabel)
        self.compareListTab2 = QtGui.QListView(self.layoutWidget2)
        self.compareListTab2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.compareListTab2.setObjectName(_fromUtf8("compareListTab2"))
        self.verticalLayout_6.addWidget(self.compareListTab2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.addCondBtn = QtGui.QPushButton(self.layoutWidget2)
        self.addCondBtn.setObjectName(_fromUtf8("addCondBtn"))
        self.verticalLayout_6.addWidget(self.addCondBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 42, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.valueLabel = QtGui.QLabel(self.layoutWidget2)
        self.valueLabel.setObjectName(_fromUtf8("valueLabel"))
        self.verticalLayout_7.addWidget(self.valueLabel)
        self.value1LineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.value1LineEdit.setObjectName(_fromUtf8("value1LineEdit"))
        self.verticalLayout_7.addWidget(self.value1LineEdit)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.searchText = QtGui.QTextBrowser(self.layoutWidget2)
        self.searchText.setAcceptDrops(False)
        self.searchText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchText.setDocumentTitle(_fromUtf8(""))
        self.searchText.setAcceptRichText(True)
        self.searchText.setOpenLinks(False)
        self.searchText.setObjectName(_fromUtf8("searchText"))
        self.verticalLayout_7.addWidget(self.searchText)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.descrLabelTab2 = QtGui.QLabel(self.layoutWidget2)
        self.descrLabelTab2.setMinimumSize(QtCore.QSize(0, 60))
        self.descrLabelTab2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.descrLabelTab2.setFrameShadow(QtGui.QFrame.Sunken)
        self.descrLabelTab2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descrLabelTab2.setWordWrap(True)
        self.descrLabelTab2.setObjectName(_fromUtf8("descrLabelTab2"))
        self.verticalLayout_8.addWidget(self.descrLabelTab2)
        self.mainTabs.addTab(self.condTab, _fromUtf8(""))
        self.sortTab = QtGui.QWidget()
        self.sortTab.setObjectName(_fromUtf8("sortTab"))
        self.layoutWidget3 = QtGui.QWidget(self.sortTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 781, 491))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableSortLabel = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableSortLabel.sizePolicy().hasHeightForWidth())
        self.tableSortLabel.setSizePolicy(sizePolicy)
        self.tableSortLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.tableSortLabel.setObjectName(_fromUtf8("tableSortLabel"))
        self.horizontalLayout_5.addWidget(self.tableSortLabel)
        self.tableSortCombo = QtGui.QComboBox(self.layoutWidget3)
        self.tableSortCombo.setObjectName(_fromUtf8("tableSortCombo"))
        self.horizontalLayout_5.addWidget(self.tableSortCombo)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.fieldsSortLabel = QtGui.QLabel(self.layoutWidget3)
        self.fieldsSortLabel.setObjectName(_fromUtf8("fieldsSortLabel"))
        self.verticalLayout_9.addWidget(self.fieldsSortLabel)
        self.availFieldsList = QtGui.QListView(self.layoutWidget3)
        self.availFieldsList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.availFieldsList.setObjectName(_fromUtf8("availFieldsList"))
        self.verticalLayout_9.addWidget(self.availFieldsList)
        self.horizontalLayout_7.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem2 = QtGui.QSpacerItem(10, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.addFieldBtn = QtGui.QPushButton(self.layoutWidget3)
        self.addFieldBtn.setObjectName(_fromUtf8("addFieldBtn"))
        self.verticalLayout_10.addWidget(self.addFieldBtn)
        self.delFieldBtn = QtGui.QPushButton(self.layoutWidget3)
        self.delFieldBtn.setObjectName(_fromUtf8("delFieldBtn"))
        self.verticalLayout_10.addWidget(self.delFieldBtn)
        self.clearFieldsBtn = QtGui.QPushButton(self.layoutWidget3)
        self.clearFieldsBtn.setObjectName(_fromUtf8("clearFieldsBtn"))
        self.verticalLayout_10.addWidget(self.clearFieldsBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.fieldsSortedLabel = QtGui.QLabel(self.layoutWidget3)
        self.fieldsSortedLabel.setObjectName(_fromUtf8("fieldsSortedLabel"))
        self.horizontalLayout_6.addWidget(self.fieldsSortedLabel)
        spacerItem4 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.ascBtn = QtGui.QToolButton(self.layoutWidget3)
        self.ascBtn.setMinimumSize(QtCore.QSize(32, 32))
        self.ascBtn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/ascending_256.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ascBtn.setIcon(icon1)
        self.ascBtn.setIconSize(QtCore.QSize(32, 32))
        self.ascBtn.setObjectName(_fromUtf8("ascBtn"))
        self.horizontalLayout_6.addWidget(self.ascBtn)
        self.desBtn = QtGui.QToolButton(self.layoutWidget3)
        self.desBtn.setMinimumSize(QtCore.QSize(32, 32))
        self.desBtn.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/descending_256.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.desBtn.setIcon(icon2)
        self.desBtn.setIconSize(QtCore.QSize(32, 32))
        self.desBtn.setObjectName(_fromUtf8("desBtn"))
        self.horizontalLayout_6.addWidget(self.desBtn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.sortedFieldsList = QtGui.QListView(self.layoutWidget3)
        self.sortedFieldsList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sortedFieldsList.setObjectName(_fromUtf8("sortedFieldsList"))
        self.verticalLayout_11.addWidget(self.sortedFieldsList)
        self.horizontalLayout_7.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.descrLabelTab3 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descrLabelTab3.sizePolicy().hasHeightForWidth())
        self.descrLabelTab3.setSizePolicy(sizePolicy)
        self.descrLabelTab3.setMinimumSize(QtCore.QSize(60, 60))
        self.descrLabelTab3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.descrLabelTab3.setFrameShadow(QtGui.QFrame.Sunken)
        self.descrLabelTab3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descrLabelTab3.setWordWrap(True)
        self.descrLabelTab3.setObjectName(_fromUtf8("descrLabelTab3"))
        self.verticalLayout_12.addWidget(self.descrLabelTab3)
        self.mainTabs.addTab(self.sortTab, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.mainTabs)
        self.buttonBox = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_13.addWidget(self.buttonBox)
        self.tableLabel.setBuddy(self.tableCombo)
        self.fieldsLabel.setBuddy(self.fieldsListTab2)
        self.compLabel.setBuddy(self.compareListTab2)
        self.valueLabel.setBuddy(self.value1LineEdit)
        self.tableSortLabel.setBuddy(self.tableSortCombo)
        self.fieldsSortLabel.setBuddy(self.availFieldsList)
        self.fieldsSortedLabel.setBuddy(self.sortedFieldsList)

        self.retranslateUi(Dialog)
        self.mainTabs.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.mainTabs, self.tableSortCombo)
        Dialog.setTabOrder(self.tableSortCombo, self.availFieldsList)
        Dialog.setTabOrder(self.availFieldsList, self.addFieldBtn)
        Dialog.setTabOrder(self.addFieldBtn, self.delFieldBtn)
        Dialog.setTabOrder(self.delFieldBtn, self.clearFieldsBtn)
        Dialog.setTabOrder(self.clearFieldsBtn, self.sortedFieldsList)
        Dialog.setTabOrder(self.sortedFieldsList, self.ascBtn)
        Dialog.setTabOrder(self.ascBtn, self.desBtn)
        Dialog.setTabOrder(self.desBtn, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.searchText)
        Dialog.setTabOrder(self.searchText, self.newQueryBtn)
        Dialog.setTabOrder(self.newQueryBtn, self.fieldsListTab2)
        Dialog.setTabOrder(self.fieldsListTab2, self.compareListTab2)
        Dialog.setTabOrder(self.compareListTab2, self.value1LineEdit)
        Dialog.setTabOrder(self.value1LineEdit, self.addCondBtn)
        Dialog.setTabOrder(self.addCondBtn, self.tableCombo)
        Dialog.setTabOrder(self.tableCombo, self.typeListWidget)
        Dialog.setTabOrder(self.typeListWidget, self.currentViewsList)
        Dialog.setTabOrder(self.currentViewsList, self.newQueryName)
        Dialog.setTabOrder(self.newQueryName, self.editQueryBtn)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Records - Advanced Query", None))
        self.newQueryBtn.setText(_translate("Dialog", "Create a new query", None))
        self.newQueryName.setPlaceholderText(_translate("Dialog", "query_name", None))
        self.editQueryBtn.setText(_translate("Dialog", "Edit an existing query", None))
        self.viewsGroupBox.setTitle(_translate("Dialog", "Current Queries / Views", None))
        self.typeGroupBox.setTitle(_translate("Dialog", "Type of Query", None))
        self.descrLabelTab1.setText(_translate("Dialog", "Description", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.queryTypeTab), _translate("Dialog", "&Query Type", None))
        self.tableLabel.setText(_translate("Dialog", "&Table:", None))
        self.fieldsLabel.setText(_translate("Dialog", "&Fields:", None))
        self.compLabel.setText(_translate("Dialog", "Compare &By:", None))
        self.addCondBtn.setText(_translate("Dialog", "&Add Another Comparison", None))
        self.valueLabel.setText(_translate("Dialog", "&Value:", None))
        self.searchText.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">The search terms will appear in here</span></p></body></html>", None))
        self.descrLabelTab2.setText(_translate("Dialog", "Description", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.condTab), _translate("Dialog", "&Conditions", None))
        self.tableSortLabel.setText(_translate("Dialog", "&Table:", None))
        self.fieldsSortLabel.setText(_translate("Dialog", "&Fields:", None))
        self.addFieldBtn.setText(_translate("Dialog", "&Add", None))
        self.delFieldBtn.setText(_translate("Dialog", "&Remove", None))
        self.clearFieldsBtn.setText(_translate("Dialog", "C&lear All", None))
        self.fieldsSortedLabel.setText(_translate("Dialog", "Fields to &sort on", None))
        self.ascBtn.setToolTip(_translate("Dialog", "Ascending", None))
        self.desBtn.setToolTip(_translate("Dialog", "Descending", None))
        self.descrLabelTab3.setText(_translate("Dialog", "Description", None))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.sortTab), _translate("Dialog", "&Sort", None))

from ui.dialogs import dialog_rc
